name: GENUARY 2021
title: GENUARY 2021
description: GENUARY 2021 is an artificially generated month of creative coding. 31 prompts for 31 days of making beautiful PROGRAMS / ALGORITHMS / MACHINES / AUTOMATONS.
keywords: generative,generative art,genuary,genuary 2021,creative coding,code,programming

lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

theme: jekyll-theme-minimal