name: GENUARY 2021
title: GENUARY 2021
description: GENUARY 2021 is an artificially generated month of time where we build code that makes beautiful things. It happens during the month of January in 2021.

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
